[package]
name = "pacman-bintrans"
version = "0.1.0"
authors = ["user"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.31"
log = "0.4.11"
env_logger = "0.7.1"
sct = "0.6.0"
reqwest = { version = "0.10.7", features=["stream"] }
structopt = "0.3.16"
tokio = { version = "0.2", features = ["macros"] }
futures-util = "0.3.5"
toml = "0.5.6"
serde = "1.0.115"
blake2 = "0.9.0"
data-encoding = "2.3.0"
rustls = "0.18.0"
x509-parser = "0.7.0"
der-parser = "3"
ct-logs = "0.7.0"
nom = "5.1.2"
